spring:
  datasource:
    username: root
    password: mxr2017
    url: jdbc:mysql://127.0.0.1:3306/chess?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver